/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/printer/Printer.e.vm.java
 */
package fr.jaxio.printer;

import java.util.Locale;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.jaxio.domain.SavedSearch;
import fr.jaxio.printer.DiscoverablePrinter;

/**
 * {@link org.springframework.format.Printer} for {@link SavedSearch} 
 *
 * @see org.springframework.format.Printer
 * @see DiscoverablePrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SavedSearchPrinter extends DiscoverablePrinter<SavedSearch> {
    public SavedSearchPrinter() {
        super(SavedSearch.class);
    }

    @Override
    public String print(SavedSearch savedSearch, Locale locale) {
        if (savedSearch == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, savedSearch.getName());
        return ret.toString();
    }
}