/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/dao/DAOImpl.e.vm.java
 */
package fr.jaxio.dao;

import static fr.jaxio.domain.Document_.documentBinary;
import static fr.jaxio.domain.Document_.documentFileName;
import javax.inject.Named;
import javax.inject.Singleton;
import fr.jaxio.dao.DocumentDao;
import fr.jaxio.dao.support.GenericDao;
import fr.jaxio.domain.Document;

/**
 * JPA 2 Data Access Object for {@link Document}.
 * Note: do not use @Transactional in the DAO layer.
 */
@Named
@Singleton
public class DocumentDao extends GenericDao<Document, String> {
    public DocumentDao() {
        super(Document.class, documentBinary, documentFileName);
    }
}